### PR TITLE
Fixed scripts due to bootstrap refactoring

### LINKED ISSUE #956: Validation tests failing
**Operating System and version**
Linux PR validation job server.

**Traceback and/or steps to reproduce**

```python
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<start_communities() done, defined at main.py:27> exception=AttributeError("'IsolatedDiscoveryCommunity' object has no attribute 'resolve_dns_bootstrap_addresses'")>
Traceback (most recent call last):
  File "main.py", line 105, in start_communities
    'IsolatedIdentityCommunity': IsolatedIdentityCommunity
  File "/home/jenkins/ci/workspace/ipv8/validate_attestation_tutorial/pyipv8/ipv8_service.py", line 134, in __init__
    self.on_start.append((getattr(overlay_instance, config[0]), config[1:]))
AttributeError: 'IsolatedDiscoveryCommunity' object has no attribute 'resolve_dns_bootstrap_addresses'
```

Broken by #955, did not validate before merge.

### LINKED ISSUE #958: peer_discovery.py stresstest failing
**Operating System and version**
performance_peer_discovery builder

**Traceback and/or steps to reproduce**

```python
future: <Task finished coro=<start_communities() done, defined at peer_discovery.py:58> exception=KeyError('bootstrappers')>
Traceback (most recent call last):
  File "peer_discovery.py", line 80, in start_communities
    ipv8 = IPv8(configuration)
  File "/home/jenkins/ci/workspace/ipv8/performance_peer_discovery/ipv8_service.py", line 135, in __init__
    for bootstrapper in overlay['bootstrappers']:
KeyError: 'bootstrappers'
```

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #956
Fixes #958

This PR:

 - Fixes validation tests not using new bootstrapping logic.
 - Fixes identity community not spawning with a bootstrapper.
 - Fixes `peer_discovery.py` stresstest not using new bootstrapping logic.

### CODE REVIEW

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
The remaining Flake8 and Pylint violations were already present (style refactorings to existing code are not part of this PR).

Ready for review.

**Review by egbertbouman — APPROVED** [review]
