### ISSUE TITLE
Validation tests failing

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#956]
**Operating System and version**
Linux PR validation job server.

**Traceback and/or steps to reproduce**

```python
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<start_communities() done, defined at main.py:27> exception=AttributeError("'IsolatedDiscoveryCommunity' object has no attribute 'resolve_dns_bootstrap_addresses'")>
Traceback (most recent call last):
  File "main.py", line 105, in start_communities
    'IsolatedIdentityCommunity': IsolatedIdentityCommunity
  File "/home/jenkins/ci/workspace/ipv8/validate_attestation_tutorial/pyipv8/ipv8_service.py", line 134, in __init__
    self.on_start.append((getattr(overlay_instance, config[0]), config[1:]))
AttributeError: 'IsolatedDiscoveryCommunity' object has no attribute 'resolve_dns_bootstrap_addresses'
```

Broken by #955, did not validate before merge.

**Comment by qstokkink** [comment]
Another error:

```python
future: <Task finished name='Task-1' coro=<start_communities() done, defined at /home/quinten/Documents/py-ipv8/doc/basics/overlay_tutorial_4.py:22> exception=TypeError("add_overlay() missing 1 required positional argument: 'on_start'")>
Traceback (most recent call last):
  File "/home/quinten/Documents/py-ipv8/doc/basics/overlay_tutorial_4.py", line 29, in start_communities
    builder.add_overlay("MyCommunity", "my peer", [WalkerDefinition(Strategy.RandomWalk, 10, {'timeout': 3.0})], {},
TypeError: add_overlay() missing 1 required positional argument: 'on_start'
```
